### ISSUE TITLE
[BUG] NPE when removeContainers is null

### ISSUE THREAD

**Issue by raydouglass** [gpuopenanalytics/remote-docker-plugin#25]
Affects v0.0.3. I think it only occurs if you have an existing job created with v0.0.2 and then upgrade the plugin to v0.0.3.

I think instead of directly accessing `removeContainers`, it should us `isRemoveContainers()` which handles if the value is null.

```
java.lang.NullPointerException
	at com.gpuopenanalytics.jenkins.remotedocker.RemoteDockerBuildWrapper.setUp(RemoteDockerBuildWrapper.java:132)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1816)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

Work around: edit the job's config and save it without changes.

**Comment by raydouglass** [comment]
With the v0.0.5 refactoring, this is no longer needed.
