### ISSUE TITLE
Side container do not work

### ISSUE THREAD

**Issue by raydouglass** [gpuopenanalytics/remote-docker-plugin#44]
When configuring a side container, the main container fails to start due to multiple networks:

```
12:07:01 $ docker network create 0fb37e01-bd0f-4207-aead-be2286847ef4
12:07:01 $ docker run -t -d --network bridge --network 0ba8e586a6e666c77c8ce78a367ff7d3ee47308cbe455b1dde671288ff8ad821 --name selenium-server selenium/standalone-firefox:83.0-geckodriver-0.28-20201119
12:07:01 docker: conflicting options: cannot attach both user-defined and non-user-defined network-modes.
12:07:01 See 'docker run --help'.
12:07:01 FATAL: Failed to start docker image
12:07:01 java.io.IOException: Failed to start docker image
12:07:01 	at com.gpuopenanalytics.jenkins.remotedocker.DockerState.launchContainer(DockerState.java:227)
12:07:01 	at com.gpuopenanalytics.jenkins.remotedocker.DockerState.launchContainers(DockerState.java:127)
12:07:01 	at com.gpuopenanalytics.jenkins.remotedocker.RemoteDockerBuildWrapper.setUp(RemoteDockerBuildWrapper.java:132)
12:07:01 	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
12:07:01 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
12:07:01 	at hudson.model.Run.execute(Run.java:1894)
12:07:01 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:07:01 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:07:01 	at hudson.model.Executor.run(Executor.java:428)
```

**Comment by raydouglass** [comment]
This was fixed in https://github.com/gpuopenanalytics/remote-docker-plugin/pull/45
